"""a2: candidate gates, rejection codes, selection bookkeeping."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

REJ_UNSUPPORTED = "unsupported_format"
REJ_THUMBS = "thumbs_artifact"
REJ_OVERSIZE = "oversize"
REJ_LICENSE = "license_blocked"
REJ_OUTRANKED = "outranked"
REJ_FETCH = "fetch_failed"
REJ_CONVERT = "convert_failed"
ALREADY = "already_available_locally"

WEB_FORMATS = {"glb", "gltf", "obj"}
SERVER_FORMATS = {"usd"}


def gate(candidate, globals_cfg):
    key = candidate.metadata.get("key", "")
    if ".thumbs" in key:
        return (REJ_THUMBS, f"thumbnail artifact: {key}")
    allowed = SERVER_FORMATS if candidate.provider == "nvidia_server" else WEB_FORMATS
    fmt = candidate.format.lower()
    if fmt not in allowed:
        return (REJ_UNSUPPORTED, f"format {fmt!r} not in {sorted(allowed)}")
    size = candidate.metadata.get("size_bytes")
    if size and size > globals_cfg.get("max_size_bytes", 200_000_000):
        return (REJ_OVERSIZE, f"{size} bytes over limit")
    if globals_cfg.get("license_gate") and str(candidate.license).lower().startswith(
        "unknown"
    ):
        return (REJ_LICENSE, candidate.license)
    return None


def gate_candidates(candidates, globals_cfg):
    records = []
    for c in candidates:
        r = gate(c, globals_cfg)
        records.append(
            {
                "candidate": c,
                "verdict": "viable" if r is None else "rejected",
                "rejection": None if r is None else {"code": r[0], "detail": r[1]},
            }
        )
    return records


def candidate_dict(c):
    return {
        "candidate_id": c.candidate_id,
        "provider": c.provider,
        "url": c.download_url,
        "format": c.format,
        "license": c.license,
        "score": c.score,
    }


def allocate_asset(category, library_dir, manifest_path):
    numbers, model_counts = set(), {}

    def note(name, count):
        m = re.match(r"^(3\d\d)_(.+)$", name)
        if not m:
            return
        numbers.add(int(m.group(1)))
        model_counts[name] = max(model_counts.get(name, 0), count)

    lib = Path(library_dir)
    if lib.is_dir():
        for p in lib.iterdir():
            if p.is_dir():
                note(p.name, len(list(p.glob("model_data*.json"))))
    mp = Path(manifest_path)
    if mp.is_file():
        for g in json.loads(mp.read_text()).get("groups", []):
            for i in g["items"]:
                note(i["asset"], i["model"] + 1)
    for name, count in sorted(model_counts.items()):
        if name.split("_", 1)[1] == category:
            return name, count
    n = max(numbers, default=300) + 1
    return f"{n}_{category}", 0


def build_manifest_group(candidate, asset, model, entry):
    key = candidate.metadata.get("key") or candidate.metadata.get(
        "path", candidate.name
    )
    item = {
        "usd": key.rsplit("/", 1)[-1],
        "asset": asset,
        "model": model,
        "category": entry["category"],
        "aliases": entry.get("aliases", [entry["category"]]),
    }
    if entry.get("colors"):
        item["colors"] = entry["colors"]
    if entry.get("flat"):
        item["flat"] = True
    return {
        "name": f"acq_{asset}",
        "prefix": key.rsplit("/", 1)[0],
        "source": candidate.provider,
        "items": [item],
    }


def append_manifest(manifest_path, group):
    p = Path(manifest_path)
    data = (
        json.loads(p.read_text())
        if p.is_file()
        else {"comment": "auto-generated by acquire_batch", "groups": []}
    )
    data["groups"] = [g for g in data["groups"] if g["name"] != group["name"]] + [group]
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, indent=1, ensure_ascii=False))
    return p


def pinned_candidate(entry):
    from agenticsim.openxsim.assets import AssetCandidate

    pin = entry["pinned"]
    key = f"{pin['prefix'].rstrip('/')}/{pin['usd']}"
    return AssetCandidate(
        candidate_id=f"pinned:{key}",
        name=pin["usd"],
        category=entry["category"],
        download_url=key,
        source_page=key,
        format="usd",
        provider="nvidia_server",
        license="unknown (NVIDIA Omniverse asset server; pinned_by_user)",
        score=0.0,
        metadata={"key": key, "pinned_by_user": True},
    )


def write_evidence(
    path, *, run_id, providers_snapshot, categories, categories_input=None
):
    payload = {
        "schema": "envgen.asset_selection_evidence.v1",
        "run_id": run_id,
        "providers": providers_snapshot,
        "categories": categories,
    }
    if categories_input is not None:
        payload["categories_sha256"] = hashlib.sha256(
            json.dumps(categories_input, sort_keys=True).encode()
        ).hexdigest()
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(payload, indent=1, ensure_ascii=False))
