"""Generated by AgenticSim Open-X-Sim."""
from metasim.scenario.objects import PrimitiveCubeCfg, RigidObjCfg
from metasim.scenario.scenario import ScenarioCfg

objects = [
    PrimitiveCubeCfg(**{'name': 'red_block', 'size': [0.05, 0.05, 0.05], 'color': [1.0, 0.0, 0.0], 'mass': 0.05, 'default_position': [-0.2, 0.015, 0.766], 'default_orientation': [1.0, 0.0, 0.0, 0.0], 'fix_base_link': False}),
]
cfg = ScenarioCfg(objects=objects, gravity=(0.0, 0.0, -9.81), headless=True, simulator=None)
