"""Generated by AgenticSim Open-X-Sim."""
from metasim.scenario.objects import PrimitiveCubeCfg, RigidObjCfg
from metasim.scenario.scenario import ScenarioCfg

objects = [
    RigidObjCfg(**{'name': 'dex_cube', 'mesh_path': '/home/jingxiang/workspace/alchedata-self-improving-agents/runs/openxsim_four_workflows/assets/dex_cube/compiled/dex_cube/source.obj', 'usd_path': '/home/jingxiang/workspace/alchedata-self-improving-agents/runs/openxsim_four_workflows/assets/dex_cube/compiled/dex_cube/dex_cube.usda', 'urdf_path': '/home/jingxiang/workspace/alchedata-self-improving-agents/runs/openxsim_four_workflows/assets/dex_cube/compiled/dex_cube/dex_cube.urdf', 'mjcf_path': '/home/jingxiang/workspace/alchedata-self-improving-agents/runs/openxsim_four_workflows/assets/dex_cube/compiled/dex_cube/dex_cube.xml', 'default_position': [0.0, 0.0, 0.25], 'default_orientation': [1.0, 0.0, 0.0, 0.0], 'scale': [0.1, 0.1, 0.1], 'fix_base_link': False}),
]
cfg = ScenarioCfg(objects=objects, gravity=(0.0, 0.0, -9.81), headless=True, simulator=None)
