"""Build a versioned, hash-bound replay package from a resolved scene."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from .schema import ResolvedSceneSpec, SceneSpec


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _write_json(path: Path, value: Any) -> None:
    path.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def generated_module_source(resolved: ResolvedSceneSpec) -> str:
    payload = json.dumps(resolved.canonical_dict(), sort_keys=True, ensure_ascii=False, separators=(",", ":"))
    return (
        '"""Generated by scene_gen.builder from a validated ResolvedSceneSpec."""\n\n'
        "import json\n\n"
        "from scene_gen.envs.generated_scene import load_resolved_scene\n\n"
        f"RESOLVED_SCENE_JSON = {payload!r}\n"
        f"RESOLVED_SCENE_SHA256 = {resolved.digest()!r}\n\n"
        "def load_scene(task, resolved_scene=None):\n"
        "    payload = resolved_scene if resolved_scene is not None else json.loads(RESOLVED_SCENE_JSON)\n"
        "    return load_resolved_scene(task, payload)\n"
    )


def build_scene_package(
    spec: SceneSpec,
    resolved: ResolvedSceneSpec,
    out_dir: Path,
) -> dict[str, Any]:
    if resolved.source_scene_spec_sha256 != spec.digest():
        raise ValueError("resolved scene is not bound to the supplied SceneSpec")
    if resolved.scene_id != spec.scene_id or resolved.seed != spec.seed:
        raise ValueError("resolved scene identity does not match SceneSpec")
    root = out_dir.expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    (root / "request.txt").write_text(spec.request + "\n", encoding="utf-8")
    _write_json(root / "scene_spec.json", spec.canonical_dict())
    _write_json(root / "resolved_scene.json", resolved.canonical_dict())
    (root / "generated_scene.py").write_text(generated_module_source(resolved), encoding="utf-8")
    files = ["request.txt", "scene_spec.json", "resolved_scene.json", "generated_scene.py"]
    manifest = {
        "schema_version": "robotwin.generated_scene_package.v1",
        "scene_id": spec.scene_id,
        "seed": spec.seed,
        "source_scene_spec_sha256": spec.digest(),
        "resolved_scene_sha256": resolved.digest(),
        "asset_catalog_sha256": resolved.asset_catalog_sha256,
        "compiler_version": resolved.compiler_version,
        "entrypoint": "generated_scene.py:load_scene",
        "resolved_only_entrypoint": "scene_gen.envs.generated_scene:load_resolved_scene",
        "files": [
            {"path": relative, "sha256": _sha256(root / relative), "bytes": (root / relative).stat().st_size}
            for relative in files
        ],
    }
    _write_json(root / "package_manifest.json", manifest)
    return manifest


def verify_package(root: Path) -> dict[str, Any]:
    package_root = root.expanduser().resolve()
    manifest_path = package_root / "package_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    checks: list[dict[str, Any]] = []
    for record in manifest.get("files", []):
        path = package_root / record["path"]
        exists = path.is_file()
        digest = _sha256(path) if exists else None
        checks.append(
            {
                "path": record["path"],
                "exists": exists,
                "expected_sha256": record["sha256"],
                "actual_sha256": digest,
                "pass": exists and digest == record["sha256"],
            }
        )
    resolved = ResolvedSceneSpec.model_validate_json((package_root / "resolved_scene.json").read_text(encoding="utf-8"))
    checks.append(
        {
            "path": "resolved_scene.json#canonical_digest",
            "expected_sha256": manifest.get("resolved_scene_sha256"),
            "actual_sha256": resolved.digest(),
            "pass": resolved.digest() == manifest.get("resolved_scene_sha256"),
        }
    )
    return {
        "schema_version": "robotwin.generated_scene_package_verification.v1",
        "status": "pass" if all(item["pass"] for item in checks) else "fail",
        "checks": checks,
    }
